#    _____          _   _         _____ _                        _____             __ _
#  / ____|        | | | |       / ____(_)                       / ____|           / _(_)
# | |     __ _ ___| |_| | ___  | (___  _  ___  __ _  ___       | |     ___  _ __ | |_ _  __ _
# | |    / _` / __| __| |/ _ \  \___ \| |/ _ \/ _` |/ _ \      | |    / _ \| '_ \|  _| |/ _` |
# | |___| (_| \__ \ |_| |  __/  ____) | |  __/ (_| |  __/      | |___| (_) | | | | | | | (_| |
#  \_____\__,_|___/\__|_|\___| |_____/|_|\___|\__, |\___|       \_____\___/|_| |_|_| |_|\__, |
#                                              __/ |                                     __/ |
#                                             |___/                                     |___/
# Welcome to the Castle Siege Config file. There are a few rules when editing YML files.
# 1. NEVER, EVER use tabs. Always use 2 spaces.
# 2. A '#' means the line is commented out. The server will ignore the line.
# 3. If you delete a portion of the config, you can delete the 'config.yml' and a new one
#    will be automatically generated on the next server restart.
# ---------------------------------------------------------------------------------------


#SpawnPlatformCenter: -> the center of the spawn platform.
SpawnPlatformCenter:
  ==: org.bukkit.Location
  world: lobby1
  x: 0
  y: 96
  z: 0
  pitch: 0
  yaw: 0

GateHealth: 250

##############################
#  --  RED BASE THINGSs  --  #
##############################
RBSpawn:
  ==: org.bukkit.Location
  world: lobby1
  x: 7.5
  y: 18
  z: 99.5
  pitch: 0
  yaw: 180

# Class NPCs

RBTank:
  ==: org.bukkit.Location
  world: lobby1
  x: -10.5
  y: 15
  z: 82.5
  pitch: 0
  yaw: -90
RBWarrior:
  ==: org.bukkit.Location
  world: lobby1
  x: -9.5
  y: 15
  z: 80.5
  pitch: 0
  yaw: -90
RBArcher:
  ==: org.bukkit.Location
  world: lobby1
  x: -8.5
  y: 15
  z: 78.5
  pitch: 0
  yaw: -90
RBWizard:
  ==: org.bukkit.Location
  world: lobby1
  x: -7.5
  y: 15
  z: 76.5
  pitch: 0
  yaw: -90

  # Catapult stuff

RBCatapultNPC:
  ==: org.bukkit.Location
  world: lobby1
  x: 18.5
  y: 16
  z: 74.5
  pitch: 0
  yaw: -118
RBCatapultLaunch:
  ==: org.bukkit.Location
  world: lobby1
  x: 20.5
  y: 16
  z: 74.5
  pitch: 0
  yaw: 180
RBCatapultMid:
  ==: org.bukkit.Location
  world: lobby1
  x: 18.5
  y: 29.8
  z: 61
  pitch: 0
  yaw: 0
RBCatapultEnd:
  ==: org.bukkit.Location
  world: lobby1
  x: 12.5
  y: 15
  z: 49.5
  pitch: 0
  yaw: 180

# Gate stuff

RBGateHologram:
  ==: org.bukkit.Location
  world: lobby1
  x: 2.5
  y: 17
  z: 62.5
  pitch: 0
  yaw: 180

RBGateTop:
  ==: org.bukkit.Location
  world: lobby1
  x: 8
  y: 19
  z: 65
  pitch: 0
  yaw: 0

RBGateBottom:
  ==: org.bukkit.Location
  world: lobby1
  x: -4
  y: 15
  z: 65
  pitch: 0
  yaw: 0


##############################
#  --  BLUE BASE THINGS  --  #
##############################

BBSpawn:
  ==: org.bukkit.Location
  world: lobby1
  x: 12.5
  y: 19
  z: -110.5
  pitch: 0
  yaw: 0

# Class NPCs

BBTank:
  ==: org.bukkit.Location
  world: lobby1
  x: 30.5
  y: 16
  z: -93.5
  pitch: 0
  yaw: 90
BBWarrior:
  ==: org.bukkit.Location
  world: lobby1
  x: 29.5
  y: 16
  z: -91.5
  pitch: 0
  yaw: 90
BBArcher:
  ==: org.bukkit.Location
  world: lobby1
  x: 28.5
  y: 16
  z: -89.5
  pitch: 0
  yaw: 90
BBWizard:
  ==: org.bukkit.Location
  world: lobby1
  x: 27.5
  y: 16
  z: -87.5
  pitch: 0
  yaw: 90

  # Catapult stuff

BBCatapultNPC:
  ==: org.bukkit.Location
  world: lobby1
  x: 1.5
  y: 17
  z: -85.5
  pitch: 0
  yaw: -118
BBCatapultLaunch:
  ==: org.bukkit.Location
  world: lobby1
  x: -0.5
  y: 16
  z: -85.5
  pitch: 0
  yaw: 180
BBCatapultMid:
  ==: org.bukkit.Location
  world: lobby1
  x: 1.85
  y: 29.8
  z: -72
  pitch: 0
  yaw: 0
BBCatapultEnd:
  ==: org.bukkit.Location
  world: lobby1
  x: 7.5
  y: 15
  z: -61.5
  pitch: 0
  yaw: 180

# Gate stuff

BBGateHologram:
  ==: org.bukkit.Location
  world: lobby1
  x: 17.5
  y: 18
  z: -75.5
  pitch: 0
  yaw: 180

BBGateTop:
  ==: org.bukkit.Location
  world: lobby1
  x: 11
  y: 20
  z: -77
  pitch: 0
  yaw: 0

BBGateBottom:
  ==: org.bukkit.Location
  world: lobby1
  x: 23
  y: 16
  z: -77
  pitch: 0
  yaw: 0




