name: CastleSiege
version: ${version}
main: dev.foxikle.castlesiege.CastleSiege
api-version: '1.20'
website: foxikle.dev
commands:
  test:
    description: Creates the platform -- For now
  class:
    description: Sets your class